; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{88E5A25F-8748-458F-BB14-812F2851CFC5}
AppName=Универсальный калькулятор
AppVersion=1.0
;AppVerName=Универсальный калькулятор 1.0
DefaultDirName={autopf}\Универсальный калькулятор
UninstallDisplayIcon={app}\UniversalCalculator.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=D:\NSTU\Prog\ТРПО\4 лаба\UniversalCalculator
OutputBaseFilename=UniversalCalculator_Setup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\NSTU\Prog\ТРПО\4 лаба\UniversalCalculator\bin\Release\net8.0-windows\win-x64\publish\UniversalCalculator.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\NSTU\Prog\ТРПО\4 лаба\UniversalCalculator\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Универсальный калькулятор"; Filename: "{app}\UniversalCalculator.exe"
Name: "{autodesktop}\Универсальный калькулятор"; Filename: "{app}\UniversalCalculator.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\UniversalCalculator.exe"; Description: "{cm:LaunchProgram,Универсальный калькулятор}"; Flags: nowait postinstall skipifsilent

